language: ruby
rvm:
- 2.1.1
- 1.9.3
- jruby-19mode
bundler_args: "--without development"
before_install:
- gem install bundler -v 1.5.2
script: bundle exec rake --trace
notifications:
  email:
    on_success: never
    on_failure: change
services:
- redis-server
env:
  matrix:
    secure: eiDhDgp8jBYKZVOqe891g4StnFsqRXcQwlDSnXthRSuWNMd6oFyFOo/s9aXd9lNFkaTBnSAFrUvywH1t2+H3j+cPMn/91W2s2Ldc+SxVxjrY3mWyr6NIudro/rdK7nIfIcWJFtm0teSXg/1nRPZt0qlXc4bZmvwvN3T8MvdgI2I=
